= Dog Game Engin
Thomas Richner(c) 2020
Version 0.1, 2020-12-24
:sectnums:
:toc:
:graphvizdot: /usr/local/bin/dot

== Board

== Second section

More test

[graphviz]
....
strict digraph {
  BN3 [fillcolor = "#0000FF", style = "filled"]
  BN3 -> BN4
  BN2 -> BN3

  GN7 [fillcolor = "#00FF00", style = "filled"]
  GN7 -> GN8
  GN6 -> GN7

  GN8 [fillcolor = "#00FF00", style = "filled"]
  GN8 -> GN9
  GN7 -> GN8

  GN10 [fillcolor = "#00FF00", style = "filled"]
  GN10 -> GN11
  GN9 -> GN10

  RN15 [fillcolor = "#FF0000", style = "filled"]
  RN15 -> YS0
  RN14 -> RN15

  BH1 [fillcolor = "#0000FF", style = "filled"]
  BH1 -> BS0

  BF4 [fillcolor = "#0000FF", style = "filled"]

  BF3 [fillcolor = "#0000FF", style = "filled"]
  BF3 -> BF4

  GN15 [fillcolor = "#00FF00", style = "filled"]
  GN15 -> RS0
  GN14 -> GN15

  RF2 [fillcolor = "#FF0000", style = "filled"]
  RF2 -> RF3

  YF3 [fillcolor = "#FFFF00", style = "filled"]
  YF3 -> YF4

  YN14 [fillcolor = "#FFFF00", style = "filled"]
  YN14 -> YN15
  YN13 -> YN14

  YN9 [fillcolor = "#FFFF00", style = "filled"]
  YN9 -> YN10
  YN8 -> YN9

  BN6 [fillcolor = "#0000FF", style = "filled"]
  BN6 -> BN7
  BN5 -> BN6

  BN11 [fillcolor = "#0000FF", style = "filled"]
  BN11 -> BN12
  BN10 -> BN11

  GH2 [fillcolor = "#00FF00", style = "filled"]
  GH2 -> GS0

  GN9 [fillcolor = "#00FF00", style = "filled"]
  GN9 -> GN10
  GN8 -> GN9

  RH2 [fillcolor = "#FF0000", style = "filled"]
  RH2 -> RS0

  RN1 [fillcolor = "#FF0000", style = "filled"]
  RN1 -> RN2
  RS0 -> RN1

  YH4 [fillcolor = "#FFFF00", style = "filled"]
  YH4 -> YS0

  GN14 [fillcolor = "#00FF00", style = "filled"]
  GN14 -> GN15
  GN13 -> GN14

  YN4 [fillcolor = "#FFFF00", style = "filled"]
  YN4 -> YN5
  YN3 -> YN4

  YN8 [fillcolor = "#FFFF00", style = "filled"]
  YN8 -> YN9
  YN7 -> YN8

  GN13 [fillcolor = "#00FF00", style = "filled"]
  GN13 -> GN14
  GN12 -> GN13

  RN4 [fillcolor = "#FF0000", style = "filled"]
  RN4 -> RN5
  RN3 -> RN4

  RN14 [fillcolor = "#FF0000", style = "filled"]
  RN14 -> RN15
  RN13 -> RN14

  YH3 [fillcolor = "#FFFF00", style = "filled"]
  YH3 -> YS0

  GS0 [fillcolor = "#00FF00", style = "filled"]
  GS0 -> GF1
  GS0 -> GN1
  BN15 -> GS0

  RN12 [fillcolor = "#FF0000", style = "filled"]
  RN12 -> RN13
  RN11 -> RN12

  YH2 [fillcolor = "#FFFF00", style = "filled"]
  YH2 -> YS0

  BF1 [fillcolor = "#0000FF", style = "filled"]
  BF1 -> BF2

  BN4 [fillcolor = "#0000FF", style = "filled"]
  BN4 -> BN5
  BN3 -> BN4

  BN12 [fillcolor = "#0000FF", style = "filled"]
  BN12 -> BN13
  BN11 -> BN12

  GF3 [fillcolor = "#00FF00", style = "filled"]
  GF3 -> GF4

  YF4 [fillcolor = "#FFFF00", style = "filled"]

  YN11 [fillcolor = "#FFFF00", style = "filled"]
  YN11 -> YN12
  YN10 -> YN11

  BS0 [fillcolor = "#0000FF", style = "filled"]
  BS0 -> BF1
  BS0 -> BN1
  YN15 -> BS0

  GN11 [fillcolor = "#00FF00", style = "filled"]
  GN11 -> GN12
  GN10 -> GN11

  YH1 [fillcolor = "#FFFF00", style = "filled"]
  YH1 -> YS0

  YN12 [fillcolor = "#FFFF00", style = "filled"]
  YN12 -> YN13
  YN11 -> YN12

  GN1 [fillcolor = "#00FF00", style = "filled"]
  GN1 -> GN2
  GS0 -> GN1

  BN5 [fillcolor = "#0000FF", style = "filled"]
  BN5 -> BN6
  BN4 -> BN5

  BN10 [fillcolor = "#0000FF", style = "filled"]
  BN10 -> BN11
  BN9 -> BN10

  GN5 [fillcolor = "#00FF00", style = "filled"]
  GN5 -> GN6
  GN4 -> GN5

  RF4 [fillcolor = "#FF0000", style = "filled"]

  YF2 [fillcolor = "#FFFF00", style = "filled"]
  YF2 -> YF3

  YN2 [fillcolor = "#FFFF00", style = "filled"]
  YN2 -> YN3
  YN1 -> YN2

  YS0 [fillcolor = "#FFFF00", style = "filled"]
  YS0 -> YF1
  YS0 -> YN1
  RN15 -> YS0

  BN2 [fillcolor = "#0000FF", style = "filled"]
  BN2 -> BN3
  BN1 -> BN2

  BN14 [fillcolor = "#0000FF", style = "filled"]
  BN14 -> BN15
  BN13 -> BN14

  GH3 [fillcolor = "#00FF00", style = "filled"]
  GH3 -> GS0

  RS0 [fillcolor = "#FF0000", style = "filled"]
  RS0 -> RF1
  RS0 -> RN1
  GN15 -> RS0

  RN3 [fillcolor = "#FF0000", style = "filled"]
  RN3 -> RN4
  RN2 -> RN3

  RN6 [fillcolor = "#FF0000", style = "filled"]
  RN6 -> RN7
  RN5 -> RN6

  YN3 [fillcolor = "#FFFF00", style = "filled"]
  YN3 -> YN4
  YN2 -> YN3

  YN15 [fillcolor = "#FFFF00", style = "filled"]
  YN15 -> BS0
  YN14 -> YN15

  BH4 [fillcolor = "#0000FF", style = "filled"]
  BH4 -> BS0

  GF2 [fillcolor = "#00FF00", style = "filled"]
  GF2 -> GF3

  RH1 [fillcolor = "#FF0000", style = "filled"]
  RH1 -> RS0

  RN5 [fillcolor = "#FF0000", style = "filled"]
  RN5 -> RN6
  RN4 -> RN5

  YF1 [fillcolor = "#FFFF00", style = "filled"]
  YF1 -> YF2

  BH2 [fillcolor = "#0000FF", style = "filled"]
  BH2 -> BS0

  BN9 [fillcolor = "#0000FF", style = "filled"]
  BN9 -> BN10
  BN8 -> BN9

  BN15 [fillcolor = "#0000FF", style = "filled"]
  BN15 -> GS0
  BN14 -> BN15

  GN4 [fillcolor = "#00FF00", style = "filled"]
  GN4 -> GN5
  GN3 -> GN4

  RN7 [fillcolor = "#FF0000", style = "filled"]
  RN7 -> RN8
  RN6 -> RN7

  RN9 [fillcolor = "#FF0000", style = "filled"]
  RN9 -> RN10
  RN8 -> RN9

  RN11 [fillcolor = "#FF0000", style = "filled"]
  RN11 -> RN12
  RN10 -> RN11

  RN8 [fillcolor = "#FF0000", style = "filled"]
  RN8 -> RN9
  RN7 -> RN8

  RN10 [fillcolor = "#FF0000", style = "filled"]
  RN10 -> RN11
  RN9 -> RN10

  YN10 [fillcolor = "#FFFF00", style = "filled"]
  YN10 -> YN11
  YN9 -> YN10

  GH1 [fillcolor = "#00FF00", style = "filled"]
  GH1 -> GS0

  GF1 [fillcolor = "#00FF00", style = "filled"]
  GF1 -> GF2

  RH4 [fillcolor = "#FF0000", style = "filled"]
  RH4 -> RS0

  RF1 [fillcolor = "#FF0000", style = "filled"]
  RF1 -> RF2

  RN2 [fillcolor = "#FF0000", style = "filled"]
  RN2 -> RN3
  RN1 -> RN2

  BN1 [fillcolor = "#0000FF", style = "filled"]
  BN1 -> BN2
  BS0 -> BN1

  BN7 [fillcolor = "#0000FF", style = "filled"]
  BN7 -> BN8
  BN6 -> BN7

  BN13 [fillcolor = "#0000FF", style = "filled"]
  BN13 -> BN14
  BN12 -> BN13

  GN3 [fillcolor = "#00FF00", style = "filled"]
  GN3 -> GN4
  GN2 -> GN3

  GN12 [fillcolor = "#00FF00", style = "filled"]
  GN12 -> GN13
  GN11 -> GN12

  RH3 [fillcolor = "#FF0000", style = "filled"]
  RH3 -> RS0

  YN6 [fillcolor = "#FFFF00", style = "filled"]
  YN6 -> YN7
  YN5 -> YN6

  YN7 [fillcolor = "#FFFF00", style = "filled"]
  YN7 -> YN8
  YN6 -> YN7

  BH3 [fillcolor = "#0000FF", style = "filled"]
  BH3 -> BS0

  BN8 [fillcolor = "#0000FF", style = "filled"]
  BN8 -> BN9
  BN7 -> BN8

  YN1 [fillcolor = "#FFFF00", style = "filled"]
  YN1 -> YN2
  YS0 -> YN1

  YN5 [fillcolor = "#FFFF00", style = "filled"]
  YN5 -> YN6
  YN4 -> YN5

  YN13 [fillcolor = "#FFFF00", style = "filled"]
  YN13 -> YN14
  YN12 -> YN13

  RN13 [fillcolor = "#FF0000", style = "filled"]
  RN13 -> RN14
  RN12 -> RN13

  GF4 [fillcolor = "#00FF00", style = "filled"]

  GN2 [fillcolor = "#00FF00", style = "filled"]
  GN2 -> GN3
  GN1 -> GN2

  GN6 [fillcolor = "#00FF00", style = "filled"]
  GN6 -> GN7
  GN5 -> GN6

  RF3 [fillcolor = "#FF0000", style = "filled"]
  RF3 -> RF4

  BF2 [fillcolor = "#0000FF", style = "filled"]
  BF2 -> BF3

  GH4 [fillcolor = "#00FF00", style = "filled"]
  GH4 -> GS0

}

....

[graphviz]
....
strict digraph {

    R0, RH1, RH2, RH3, RH4, RF1, RF2, RF3, RF4 [fillcolor = "#FF0000", style = "filled"]
    G0, GH1, GH2, GH3, GH4, GF1, GF2, GF3, GF4 [fillcolor = "#00FF00", style = "filled"]
    B0, BH1, BH2, BH3, BH4, BF1, BF2, BF3, BF4 [fillcolor = "#0000FF", style = "filled"]
    Y0, YH1, YH2, YH3, YH4, YF1, YF2, YF3, YF4 [fillcolor = "#FFFF00", style = "filled"]

    {RH4, RH3, RH2, RH1} -> R0
    R0 -> RF1 [style = "dashed"]
    R0 -> RF1 -> RF2 -> RF3 -> RF4
    R0 -> R1 -> R2 -> R3 -> R4 -> R5 -> R6 -> R7 -> R8 -> R9 -> R10 -> R11 -> R12 -> R13 -> R14 -> R15 -> Y0

    {YH4, YH3, YH2, YH1} -> Y0
    Y0 -> YF1 [style = "dashed"]
    Y0 -> YF1 -> YF2 -> YF3 -> YF4
    Y0 -> Y1 -> Y2 -> Y3 -> Y4 -> Y5 -> Y6 -> Y7 -> Y8 -> Y9 -> Y10 -> Y11 -> Y12 -> Y13 -> Y14 -> Y15 -> B0

    {BH4, BH3, BH2, BH1} -> B0
    B0 -> BF1 [style = "dashed"]
    B0 -> BF1 -> BF2 -> BF3 -> BF4
    B0 -> B1 -> B2 -> B3 -> B4 -> B5 -> B6 -> B7 -> B8 -> B9 -> B10 -> B11 -> B12 -> B13 -> B14 -> B15 -> G0

    {GH4, GH3, GH2, GH1} -> G0
    G0 -> GF1 [style = "dashed"]
    G0 -> GF1 -> GF2 -> GF3 -> GF4
    G0 -> G1 -> G2 -> G3 -> G4 -> G5 -> G6 -> G7 -> G8 -> G9 -> G10 -> G11 -> G12 -> G13 -> G14 -> G15 -> R0
}
....

* colors: red, yellow, blue, green, none
* node types: start, home, finish, normal
* edge types: forward, reverse

[source]
----
NODE_KIND = COLOR TYPE
NODE_TYPE = 'S' | 'H' | 'F' | 'N'

EDGE_DIRECTIONS = DIRECTION [ *DIRECTION ]
DIRECTION = 'f' | 'r'

COLOR := 'R' | 'Y' | 'B' | 'G' | 'N'
----

[source,json]
----
{
  "nodes": [
    {"id": "cs0", "kind":  "cs"},
    {"id": "ch1", "kind":  "ch"},
    {"id": "ch2", "kind":  "ch"},
    {"id": "ch3", "kind":  "ch"},
    {"id": "ch4", "kind":  "ch"},
    {"id": "cf1", "kind":  "cf"},
    {"id": "cf2", "kind":  "cf"},
    {"id": "cf3", "kind":  "cf"},
    {"id": "cf4", "kind":  "cf"},
    {"id": "c1", "kind":  "cn"},
    {"id": "c2", "kind":  "cn"},
    {"id": "c3", "kind":  "cn"},
    {"id": "c4", "kind":  "cn"},
    {"id": "c5", "kind":  "cn"},
    {"id": "c6", "kind":  "cn"},
    {"id": "c7", "kind":  "cn"},
    {"id": "c8", "kind":  "cn"},
    {"id": "c9", "kind":  "cn"},
    {"id": "c10", "kind":  "cn"},
    {"id": "c11", "kind":  "cn"},
    {"id": "c12", "kind":  "cn"},
    {"id": "c13", "kind":  "cn"},
    {"id": "c14", "kind":  "cn"},
    {"id": "c15", "kind":  "cn"},
    {"id": "c16", "kind":  "cn"}
  ],
  "edges": [

    "// HOME",
    {"from": "ch1", "to": "cs0", "directions": "f"},
    {"from": "ch2", "to": "cs0", "directions": "f"},
    {"from": "ch3", "to": "cs0", "directions": "f"},
    {"from": "ch4", "to": "cs0", "directions": "f"},

    "// FINISH",
    {"from": "cs0", "to": "cf1", "directions": "f"},
    {"from": "cf1", "to": "cf2", "directions": "f"},
    {"from": "cf2", "to": "cf3", "directions": "f"},
    {"from": "cf3", "to": "cf4", "directions": "f"},

    "// FORWARD",
    {"from": "pn15", "to": "cs0", "directions": "fr"},
    {"from": "cs0", "to": "cn1", "directions": "fr"},
    {"from": "cs1", "to": "cn2", "directions": "fr"},
    {"from": "cs2", "to": "cn3", "directions": "fr"},
    {"from": "cs3", "to": "cn4", "directions": "fr"},
    {"from": "cs4", "to": "cn5", "directions": "fr"},
    {"from": "cs5", "to": "cn6", "directions": "fr"},
    {"from": "cs6", "to": "cn7", "directions": "fr"},
    {"from": "cs7", "to": "cn8", "directions": "fr"},
    {"from": "cs8", "to": "cn9", "directions": "fr"},
    {"from": "cs9", "to": "cn10", "directions": "fr"},
    {"from": "cs10", "to": "cn11", "directions": "fr"},
    {"from": "cs11", "to": "cn12", "directions": "fr"},
    {"from": "cs12", "to": "cn13", "directions": "fr"},
    {"from": "cs13", "to": "cn14", "directions": "fr"},
    {"from": "cs14", "to": "cn15", "directions": "fr"},
    {"from": "cs15", "to": "ns0", "directions": "fr"}
  ]
}

----